# Generated by Django 4.2.7 on 2024-04-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='Default description', max_length=1000),
            preserve_default=False,
        ),
    ]
